version: '3.5'

services:
    mariadb:
        container_name: mariadb
        image: mariadb:lovely
        build: ./requirements/mariadb
        networks:
            - inception
        volumes:
            - mariadb_volume:/var/lib/mysql
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        image: wordpress:are
        build: ./requirements/wordpress
        networks:
            - inception
        volumes:
            - wordpress_volume:/var/www/wordpress
        environment:
            - WP_DB_NAME=$WP_DB_NAME
            - WP_DB_USER=$WP_DB_USER
            - WP_DB_PASSWORD=$WP_DB_PASSWORD
            - WP_DB_HOST=$WP_DB_HOST
            - WP_TITLE=$WP_TITLE
            - WP_ADMIN_USER=$WP_ADMIN_USER
            - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
            - WP_ADMIN_MAIL=$WP_ADMIN_MAIL
            - WP_USER=$WP_USER
            - WP_USER_MAIL=$WP_USER_MAIL
            - WP_USER_PASSWORD=$WP_USER_PASSWORD
            - WP_URL=$WP_URL
        depends_on:
            - mariadb
        restart: unless-stopped

    nginx:
        container_name: nginx
        image: nginx:we
        build: ./requirements/nginx
        ports:
            - "443:443"
        networks:
            - inception
        volumes:
            - wordpress_volume:/var/www/wordpress
        depends_on:
          - wordpress
        restart: unless-stopped

networks:
    inception:

   
volumes:
    mariadb_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/fred/data/wp_db
    wordpress_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/fred/data/wp_files
